version: '2'

services:

    wordpress:
        image: wordpress
        ports:
            - 8080:80
        volumes:
            - ./wordpress/:/var/www/html
        environment:
            WORDPRESS_DB_PASSWORD: example

    mysql:
        image: mariadb
        volumes:
            - ./db/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: example

